### ISSUE TITLE
Demo videos on project page not loading

### ISSUE THREAD

**Issue by jamesstothard** [memoavatar/memo#10]
Hi all of the videos on your project page are dead and not loading. Thought I'd let you know.

**Comment by ltzheng** [comment]
It works for me. Is it a network issue?

**Comment by jamesstothard** [comment]
Maybe, I've tried on different browsers and using my iphone and cant watch them. Is it a regional thing? 
![image](https://github.com/user-attachments/assets/1a140952-d4c1-494b-8f29-a577b330a5f7)

**Comment by jamesstothard** [comment]
I know its not mission critical but I wanted to share the page with a few colleagues to look at.

**Comment by ltzheng** [comment]
This is weird. What region are you loading the project page?

**Comment by jamesstothard** [comment]
From the United Kingdom

**Comment by ltzheng** [comment]
I'm in Singapore and it is rendering correctly. Does it work now on your side?
