### ISSUE TITLE
Traceback (most recent call last):   File "/home/sjy/data/memo/inference.py", line 251, in <module>     main()   File "/home/sjy/data/memo/inference.py", line 111, in main     pixel_values, face_emb = preprocess_image(   File "/home/sjy/anaconda3/envs/memo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context     return func(*args, **kwargs)   File "/home/sjy/data/memo/memo/utils/vision_utils.py", line 67, in preprocess_image     face_analysis = FaceAnalysis(   File "/home/sjy/anaconda3/envs/memo/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 43, in __init__     assert 'detection' in self.models AssertionError怎么解决啊这个？各位大佬

### ISSUE THREAD

**Issue by zylss-325** [memoavatar/memo#12]

**Comment by drphero** [comment]
I'm getting the same error. It occurred when trying to run it the second time. The error during the first run was:

```
Traceback (most recent call last):
  File "/workspace/memo/inference.py", line 251, in <module>
    main()
  File "/workspace/memo/inference.py", line 111, in main
    pixel_values, face_emb = preprocess_image(
  File "/opt/conda/envs/memo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/memo/memo/utils/vision_utils.py", line 67, in preprocess_image
    face_analysis = FaceAnalysis(
  File "/opt/conda/envs/memo/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "/opt/conda/envs/memo/lib/python3.10/site-packages/insightface/utils/storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "/opt/conda/envs/memo/lib/python3.10/site-packages/insightface/utils/storage.py", line 17, in download
    download_file(model_url,
  File "/opt/conda/envs/memo/lib/python3.10/site-packages/insightface/utils/download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/.zip
```

It seems there insightface isn't properly downloading its models.

**Comment by drphero** [comment]
If the failed insightface model download is what is indeed causing this, it's because vision_utils.py is passing an empty string on line 68.

**Comment by zylss-325** [comment]
> 如果 insightface 模型下载失败确实是导致这种情况的原因，那是因为 vision_utils.py 在第 68 行传递了一个空字符串。

您知道应该怎么解决吗？

**Comment by odoucet** [comment]
in vision_utils.py line 67:
```
face_analysis = FaceAnalysis(
        name="",
        root=face_analysis_model,
        providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
    )
```
leads to : `RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/.zip`

If modified like this : 
```
face_analysis = FaceAnalysis(
        name="antelopev2",
        root=face_analysis_model,
        providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
    )
```
Download is OK (but further error appears).

**Comment by drphero** [comment]
It turns out something is weird with how insightface unzips the files (causing problems for some ComfyUI nodes too). If you go to `checkpoints/misc/face_analysis/models/antelopev2` you'll see that there is another antelopev2 folder with the files there. You have two options now:

- Move the .onnx files from antelopev2/antelopev2/ to antelopev2/
- Modify that same line as earlier to `name="antelopev2/antelopev2"`

Either option should work. However, there are most likely going to be errors after that because they huggingface download URL they use for their models is wrong. In inference.py, lines 79 and 90, change the word "raw" in the URL to "resolve".

Also make sure you have cuda toolkit and cudnn installed or it will default to cpu and take an eternity.

**Comment by odoucet** [comment]
See https://github.com/memoavatar/memo/pull/17 for file downloading fix.

**Comment by zylss-325** [comment]
> 我尝试将其设置为，因为我见过的大多数使用 insightface 的东西都使用它。它成功下载，但现在我收到以下错误，我不确定它是否相关。`name="antelopev2"`
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/memo/inference.py", line 251, in <module>
>     main()
>   File "/workspace/memo/inference.py", line 124, in main
>     audio_emb, audio_length = preprocess_audio(
>   File "/opt/conda/envs/memo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/workspace/memo/memo/utils/audio_utils.py", line 89, in preprocess_audio
>     vocal_separator.load_model(os.path.basename(vocal_separator_model))
>   File "/opt/conda/envs/memo/lib/python3.10/site-packages/audio_separator/separator/separator.py", line 695, in load_model
>     model_data = self.load_model_data_using_hash(model_path)
>   File "/opt/conda/envs/memo/lib/python3.10/site-packages/audio_separator/separator/separator.py", line 669, in load_model_data_using_hash
>     raise ValueError(f"Unsupported Model File: parameters for MD5 hash {model_hash} could not be found in UVR model data file for MDX or VR arch.")
> ValueError: Unsupported Model File: parameters for MD5 hash 4b98fa6287a3d1489e969331274170cb could not be found in UVR model data file for MDX or VR arch.
> ```

您解决这个问题了吗?

**Comment by zylss-325** [comment]
> 请参阅 #17 以获取文件下载修复。

改完以后是这样的Traceback (most recent call last):
  File "/home/sjy/data/memo/inference.py", line 257, in <module>
    main()
  File "/home/sjy/data/memo/inference.py", line 86, in main
    raise RuntimeError(f"{face_analysis} file seems incorrect (too small), delete it and retry.")
RuntimeError: checkpoints/misc/face_analysis file seems incorrect (too small), delete it and retry.

**Comment by drphero** [comment]
> > 请参阅 #17 以获取文件下载修复。
> 
> 改完以后是这样的Traceback (most recent call last): File "/home/sjy/data/memo/inference.py", line 257, in main() File "/home/sjy/data/memo/inference.py", line 86, in main raise RuntimeError(f"{face_analysis} file seems incorrect (too small), delete it and retry.") RuntimeError: checkpoints/misc/face_analysis file seems incorrect (too small), delete it and retry.

I've contacted the creator of #17 with a fix for that.

**Comment by drphero** [comment]
> 怎么解决的，他更新那个代码了吗

Not yet, I just contacted them before I replied to you. If you want to try my fix, you can find it [here](https://github.com/drphero/memo/tree/huggingface-lfs-fix-v2).

**Comment by zylss-325** [comment]
> > 怎么解决的，他更新那个代码了吗
> 
> 还没有，我只是在回复你之前联系了他们。如果您想尝试我的修复方法，可以[在此处](https://github.com/drphero/memo/tree/huggingface-lfs-fix-v2)找到。确保使用 huggingface-lfs-fix-v2 分支。

是利用你这个重新部署吗?还是怎么用这个

**Comment by drphero** [comment]
> 是利用你这个重新部署吗?还是怎么用这个

Yes, until everything is merged, it's best to try the following:

1. `git clone https://github.com/drphero/memo`
2. `cd memo`
3. `git checkout huggingface-lfs-fix-v2`

The rest of the readme instructions should be fine then. But if you're using a GPU, make sure you have CUDA Toolkit and cuDNN installed or you'll be stuck using just your CPU.

**Comment by zylss-325** [comment]
> > 是利用你这个重新部署吗?还是怎么用这个
> 
> 是的，在所有内容都合并之前，最好尝试以下操作：
> 
> 1. `git clone https://github.com/drphero/memo`
> 2. `cd memo`
> 3. `git checkout huggingface-lfs-fix-v2`
> 
> 那么 readme 说明的其余部分应该没问题。但是，如果您使用的是 GPU，请确保您已安装 CUDA 工具包和 cuDNN，否则您将只能使用 CPU。

非常感谢您，用您的这个推理成功了

**Comment by NikoBele1** [comment]
> > 我尝试将其设置为，因为我见过的大多数使用 insightface 的东西都使用它。它成功下载，但现在我收到以下错误，我不确定它是否相关。`name="antelopev2"`
> > ```
> > Traceback (most recent call last):
> >   File "/workspace/memo/inference.py", line 251, in <module>
> >     main()
> >   File "/workspace/memo/inference.py", line 124, in main
> >     audio_emb, audio_length = preprocess_audio(
> >   File "/opt/conda/envs/memo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> >     return func(*args, **kwargs)
> >   File "/workspace/memo/memo/utils/audio_utils.py", line 89, in preprocess_audio
> >     vocal_separator.load_model(os.path.basename(vocal_separator_model))
> >   File "/opt/conda/envs/memo/lib/python3.10/site-packages/audio_separator/separator/separator.py", line 695, in load_model
> >     model_data = self.load_model_data_using_hash(model_path)
> >   File "/opt/conda/envs/memo/lib/python3.10/site-packages/audio_separator/separator/separator.py", line 669, in load_model_data_using_hash
> >     raise ValueError(f"Unsupported Model File: parameters for MD5 hash {model_hash} could not be found in UVR model data file for MDX or VR arch.")
> > ValueError: Unsupported Model File: parameters for MD5 hash 4b98fa6287a3d1489e969331274170cb could not be found in UVR model data file for MDX or VR arch.
> > ```
> 
> 您解决这个问题了吗?

I have the same problem. Does a solution exist?

**Comment by drphero** [comment]
> I have the same problem. Does a solution exist?

They have merged a PR into the main branch that should fix the issue. I recommend starting the setup from scratch.
