### ISSUE TITLE
I work on a wrapper for comfyui

### ISSUE THREAD

**Issue by if-ai** [memoavatar/memo#21]
seems to work on 3090 
https://github.com/if-ai/ComfyUI-IF_MemoAvatar/tree/main

**Comment by ltzheng** [comment]
Thanks! Will add to the README.

**Comment by if-ai** [comment]
Awesome! Thank you.

**Comment by Ema81xsd** [comment]
there is already a wrapper isn´t it : 
https://github.com/if-ai/ComfyUI-IF_MemoAvatar

**Comment by if-ai** [comment]
> there is already a wrapper isn´t it : https://github.com/if-ai/ComfyUI-IF_MemoAvatar

Yes that's the one

**Comment by huanggou666** [comment]
> > there is already a wrapper isn´t it : https://github.com/if-ai/ComfyUI-IF_MemoAvatar
> 
> Yes that's the one

can you share more detail , how long does it take to generate a video , can we see some result video from this comfyui node

**Comment by if-ai** [comment]
https://github.com/user-attachments/assets/7d725233-a687-45c6-a76b-9b1ebb6c1cac

These are all first tries without cherry picking it bassically works the same as the repo but in comfyui a video depends on the machine mine has a nvidia 3090 takes around 4 mins for a 5 sec video
