### ISSUE TITLE
KeyError: 'model_conf

### ISSUE THREAD

**Issue by StartHua** [memoavatar/memo#9]
File "D:\sofa\conda\envs\tgngo\Lib\site-packages\funasr\models\emotion2vec\model.py", line 45, in __init__
    cfg = OmegaConf.create(kwargs["model_conf"])
                           ~~~~~~^^^^^^^^^^^^^^
KeyError: 'model_conf

**Comment by Holmes2002** [comment]
same. Do u have any solution ?

**Comment by Holmes2002** [comment]
pip install modelscope to solve

**Comment by ltzheng** [comment]
Thanks for fixing this issue, but I think modelscope==1.20.1 is already in the project.toml. Is there any issue in our install guide?

**Comment by nitinmukesh** [comment]
@ltzheng 

Please could you help with reducing the memory usage. I am offloading vae to cpu the same way in all other similar projects to reduce memory usage and it works fine.

However this is the first time I am facing problem. The following works and reduce the VRAM usage to 5 GB but inference remains at 0% and never moves. After around 1 hours it times out.

```
pipeline = VideoPipeline(
        vae=vae,
        reference_net=reference_net,
        diffusion_net=diffusion_net,
        scheduler=noise_scheduler,
        image_proj=image_proj,
    )
    pipeline.to(device=device, dtype=weight_dtype)
    pipeline.vae.to('cpu')
```

If you can help, I think this will work on low VRAM systems.

**Comment by Holmes2002** [comment]
@ltzheng Hm no, your env file is ok, I built some custom libraries for my hardware so It caused this problem due to lack of libs
